### ISSUE TITLE
Urgent: The link to documentation not working

### ISSUE THREAD

**Issue by WasifurRahman** [bootphon/shennong#4]
Can you please take a look at the issue? 

We have a deadline in seven days and we really need the link working.

**Comment by mmmaat** [comment]
Hi, indeed our server is down since few days. Because of the covid crisis we cannot fix it for now. I'll try to publish the documentation elsewhere in the next few days.

But you can easily build a local version of the documentation, follow instructions [here](https://github.com/bootphon/shennong/blob/master/doc/source/installation.rst#build-the-documentation). Here the direct path (I suppose you are on Linux):
```bash
git clone https://github.com/bootphon/shennong.git
cd ./shennong
conda env create --name shennong -f environment.yml
conda activate shennong
make install
sudo apt install texlive texlive-latex-extra dvipng
make doc
```
Now you have the documentation built locally: `firefox ./doc/build/html/index.html`.

If you have troubles let me know I can send you the doc by email.

**Comment by WasifurRahman** [comment]
Thank you so much for helping us so promptly. It was really very helpful.

Have a nice weekend.
